DROP TABLE IF EXISTS bookmarks;

CREATE TABLE bookmarks (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        title TEXT NOT NULL,
        rating INTEGER,
        "url" TEXT NOT NULL,
        "desc" TEXT, 
        expanded BOOLEAN NOT NULL DEFAULT false 
    );